# from geometry.beam import Beam
# from geometry.dowel import Dowel
# from geometry.hole import Hole
# from geometry.joint_holes import JointHoles
# from geometry.local_network import LocalNetwork
# from geometry.global_network import GlobalNetwork
# from geometry.surface import Surface
# from geometry.shared_edge import SharedEdge
# from geometry.surface_keystone import Keystone
# from geometry.edge import *
